### ISSUE TITLE
Not able to log in.

### ISSUE THREAD

**Issue by TheMorc** [taylordotfish/harmony#11]
Hi, i was trying Harmony and i wasn't able to log in to my 2FA account. It firstly said that it did log in but any single command after that just said that i'm not logged in. I also tried with --debug switch but i haven't seen much obvious there showing that it did not log in.
(And it's real pain to get it to install on macOS.. I had to try on clean Debian)

(And also I don't think that even anyone will help me now)

**Comment by Dhamma-valence** [comment]
Yes, it has been completely broken for me as well and I'm pretty certain that this is no longer maintained seeing as how this is STILL unanswered and open 6 months later.

**Comment by grauschnabel** [comment]
The same here:

`requests.exceptions.InvalidURL: Failed to parse: https://discordapp.com/api/v6/experiments`

**Comment by taylordotfish** [comment]
Fixed in version 0.6.1.
