### ISSUE TITLE
feature: password storage

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/harmony#5]
It would be nice if harmony could remember my password and use it when I login.

I would suggest using the Python keyring module to store it in the system-dependent secret storage system:

https://pypi.python.org/pypi/keyring

**Comment by pabs3** [comment]
Another option is the secretstorage module:

https://pypi.org/project/SecretStorage/

I think it would be useful to support both the keyring and secretstorage modules, since one or the other module might not be available on older or newer distros.

**Comment by taylordotfish** [comment]
Added in version 0.7.0 using Keyring. If a pressing need to support SecretStorage arises, please open another issue or PR.

**Comment by pabs3** [comment]
Excellent thanks. For Debian at least SecretStorage wouldn't be needed.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
