### ISSUE TITLE
Google ReCaptcha not working

### ISSUE THREAD

**Issue by polarisfm** [taylordotfish/harmony#7]
Hi there. It seems there's an issue with Harmony. Google ReCaptcha submission is broken. librecaptcha works fine, I used it on another website and it was function, so it appears to be an issue with Harmony itself.

After solving the Captcha, the following is returned:

```
Successfully solved the CAPTCHA challenge.

Login failed. Errors:

captcha_key:

incorrect-captcha-sol
```

**Comment by nickolas360** [comment]
This is a [known issue with librecaptcha](https://github.com/nickolas360/librecaptcha/issues/7).

**Comment by pabs3** [comment]
This can be closed as it was filed in the wrong project.

**Comment by taylordotfish** [comment]
Yeah, when this issue was filed, it wasn't obvious that this was a problem with librecaptcha rather than Harmony, but Harmony now prints a message that links to the [relevant librecaptcha issue](https://github.com/taylordotfish/librecaptcha/issues/7) when tokens are rejected, so I'll close this.
